# Generated by Django 4.1.2 on 2023-02-17 12:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_buyer', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BidAmountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('pitch', models.CharField(blank=True, max_length=2000, null=True)),
                ('days', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_desc', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('linkedin_profile', models.URLField(blank=True, max_length=255, null=True)),
                ('github_profile', models.URLField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='buyer/images/profile_pic/default_profile_Is8arW2.png', upload_to='buyer/images/profile_pic')),
                ('resume', models.FileField(blank=True, upload_to='buyer/files/resumes')),
                ('long_description', models.TextField(null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('available', models.CharField(blank=True, max_length=255, null=True)),
                ('verification', models.BooleanField(default=False)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=45)),
                ('category_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='JobTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type_title', models.CharField(max_length=45)),
                ('job_type_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=45)),
                ('skill_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, default='seller/company/logos/default_profile.png', upload_to='seller/company/logos')),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_company', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('company_short_desc', models.CharField(max_length=100)),
                ('company_desc', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBillingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(null=True, upload_to='media/screenshot')),
                ('keyups', models.IntegerField()),
                ('mouseclicks', models.IntegerField()),
                ('duration', models.DateTimeField(auto_now_add=True, null=True)),
                ('seconds', models.FloatField(null=True)),
                ('task', models.CharField(max_length=255, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.bidamountmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostjobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=2000)),
                ('full_desc', ckeditor.fields.RichTextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('askamount', models.IntegerField(blank=True, null=True)),
                ('askamount_2', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='seller/files/Job')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('Attachment', models.FileField(blank=True, null=True, upload_to='buyer/files/Job')),
                ('category_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.jobcategorymodel')),
                ('job_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.jobtypemodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sellerprofilemodel')),
                ('skills', models.ManyToManyField(to='mainapp.skillmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_signature', models.CharField(blank=True, max_length=150)),
                ('amount', models.IntegerField()),
                ('paymentReport', models.BooleanField(default=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.buyerprofilemodel')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.postjobmodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.sellerprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.buyerprofilemodel')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sellerprofilemodel')),
            ],
        ),
        migrations.AddField(
            model_name='buyerprofilemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.jobcategorymodel'),
        ),
        migrations.AddField(
            model_name='buyerprofilemodel',
            name='skills',
            field=models.ManyToManyField(blank=True, to='mainapp.skillmodel'),
        ),
        migrations.AddField(
            model_name='buyerprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BillingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.FloatField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.bidamountmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bidamountmodel',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.buyerprofilemodel'),
        ),
        migrations.AddField(
            model_name='bidamountmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.postjobmodel'),
        ),
        migrations.CreateModel(
            name='ApplyForJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.CharField(blank=True, max_length=2000, null=True)),
                ('bidamount', models.IntegerField()),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.postjobmodel')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.buyerprofilemodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sellerprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('card_number', models.IntegerField()),
                ('expiry_date', models.DateField(max_length=8)),
                ('cvv', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
