# Generated by Django 4.1.2 on 2023-02-21 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjobmodel',
            name='deadline',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
