# Generated by Django 4.1.2 on 2023-02-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_postjobmodel_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjobmodel',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
