# Generated by Django 4.1.2 on 2023-02-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
