# Generated by Django 4.1.2 on 2023-02-27 07:06

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='unique_code',
            field=models.CharField(default=chat.models.UniqueGenerator, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.SlugField(max_length=128),
        ),
    ]
