# Generated by Django 4.1.2 on 2023-02-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_unique_code_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chatType',
            field=models.CharField(choices=[('is_chat', 'is_chat'), ('is_group', 'is_group')], default='is_chat', max_length=100),
        ),
    ]
