name: Pull request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      

    steps:
    - uses: actions/checkout@v3

         
    - name: install requirements
      run: |
        pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV

        pip install -r requirements.txt
    - name: migrations
      run: |
        source venv/bin/activate
        python manage.py makemigrations
        python manage.py makemigrations mainapp
        python manage.py makemigrations chat

    - name: migrate
      run: |
        source venv/bin/activate
        
    - name: Collect Static
      run: |
        source venv/bin/activate
        python manage.py collectstatic --noinput
   
    - name: test
      run: |
        source venv/bin/activate
        python manage.py test
